// This file will be auto-generated by Supabase CLI: npx supabase gen types typescript
// For now, we'll use a placeholder structure

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string
          full_name: string | null
          avatar_url: string | null
          bio: string | null
          website: string | null
          twitter: string | null
          github: string | null
          badges: string[] | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          username: string
          full_name?: string | null
          avatar_url?: string | null
          bio?: string | null
          website?: string | null
          twitter?: string | null
          github?: string | null
          badges?: string[] | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          username?: string
          full_name?: string | null
          avatar_url?: string | null
          bio?: string | null
          website?: string | null
          twitter?: string | null
          github?: string | null
          badges?: string[] | null
          created_at?: string
          updated_at?: string
        }
      }
      products: {
        Row: {
          id: string
          slug: string
          name: string
          tagline: string
          description: string
          image_url: string | null
          demo_url: string | null
          website_url: string | null
          github_url: string | null
          category_id: string | null
          user_id: string
          featured: boolean
          status: 'draft' | 'published' | 'archived'
          metadata: Json | null
          views_count: number
          upvotes_count: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          tagline: string
          description: string
          image_url?: string | null
          demo_url?: string | null
          website_url?: string | null
          github_url?: string | null
          category_id?: string | null
          user_id: string
          featured?: boolean
          status?: 'draft' | 'published' | 'archived'
          metadata?: Json | null
          views_count?: number
          upvotes_count?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          tagline?: string
          description?: string
          image_url?: string | null
          demo_url?: string | null
          website_url?: string | null
          github_url?: string | null
          category_id?: string | null
          user_id?: string
          featured?: boolean
          status?: 'draft' | 'published' | 'archived'
          metadata?: Json | null
          views_count?: number
          upvotes_count?: number
          created_at?: string
          updated_at?: string
        }
      }
      categories: {
        Row: {
          id: string
          name: string
          slug: string
          description: string | null
          icon: string | null
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          description?: string | null
          icon?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          description?: string | null
          icon?: string | null
          created_at?: string
        }
      }
      tags: {
        Row: {
          id: string
          name: string
          slug: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          created_at?: string
        }
      }
      product_tags: {
        Row: {
          product_id: string
          tag_id: string
          created_at: string
        }
        Insert: {
          product_id: string
          tag_id: string
          created_at?: string
        }
        Update: {
          product_id?: string
          tag_id?: string
          created_at?: string
        }
      }
      reviews: {
        Row: {
          id: string
          product_id: string
          user_id: string
          rating: number
          comment: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          product_id: string
          user_id: string
          rating: number
          comment?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          product_id?: string
          user_id?: string
          rating?: number
          comment?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      votes: {
        Row: {
          id: string
          product_id: string
          user_id: string
          vote_type: 'upvote' | 'downvote'
          created_at: string
        }
        Insert: {
          id?: string
          product_id: string
          user_id: string
          vote_type: 'upvote' | 'downvote'
          created_at?: string
        }
        Update: {
          id?: string
          product_id?: string
          user_id?: string
          vote_type?: 'upvote' | 'downvote'
          created_at?: string
        }
      }
      bookmarks: {
        Row: {
          id: string
          product_id: string
          user_id: string
          created_at: string
        }
        Insert: {
          id?: string
          product_id: string
          user_id: string
          created_at?: string
        }
        Update: {
          id?: string
          product_id?: string
          user_id?: string
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
